### ISSUE TITLE
I will like to write about us

### ISSUE THREAD

**Issue by LINCOM011** [SteemPay/steempay-wallet#7]
Hello, I want to write about us for your blog. If the avenue is still available..... Thanks and regards

**Comment by kodaxx** [comment]
Unfortunately this is already being taken care of - thanks!

**Comment by LINCOM011** [comment]
Am good at copywriting. If their Is any vacancy on copy writing will be
glad to have it...e.g About us, private policy, FAQ's and others...Thanks
and regards
